### ISSUE TITLE
define benchmark metrics for opengpt

### ISSUE THREAD

**Issue by jemmyshin** [jina-ai/opengpt#46]
UAC:
- [x] List metrics
- [x] Prepare scripts to get the metrics

**Comment by jemmyshin** [comment]
following up ticket: design a benchmark table

**Comment by jemmyshin** [comment]
@jemmyshin  propose the metrics on notion page

**Comment by jemmyshin** [comment]
https://www.notion.so/Benchmark-47e8db4128e9411eb1b33fc0cc332c69

**Comment by saahil** [comment]
Benchmark script at https://github.com/jina-ai/opengpt/blob/531fa9963cd22f1f409678ed87ace0111cc5e96c/scripts/benchmark.py#L7
