### ISSUE TITLE
support streaming output in gateway

### ISSUE THREAD

**Issue by jemmyshin** [jina-ai/opengpt#55]
two issues must be solved:

- [ ] figure out why the outputs from calling `step_generate()` for once and calling it step by step are different

for example:

this is how non-streaming generate works:
```
generated_text = model.generate(prompt, max_new_tokens, **parameters)
```

this is how streaming generate works:
```
for step in range(max_new_tokens):
    resp = model.step_generate(prompt, max_new_tokens=1, **parameters)
    past_key_values = resp.get('past_key_values')
    prompt = resp.get('generated_text')
```

- [x] support sse client to received streaming output from gateway

**Comment by saahil** [comment]
@jemmyshin please add details of the issue here.
